### ISSUE TITLE
It doesn't work for horizontal scroll div

### ISSUE THREAD

**Issue by koraykupe** [BKWLD/vue-in-viewport-mixin#11]
Hello,

I have a div with x-scroll and it has some components inside it.

I am trying to do something if a component is shown (when I scroll to right) but inViewport.now returns true for all components in the main div.

Am I missing something or it doesn't work for x-scroll stuff?

Thanks in advance.

**Comment by weotch** [comment]
Yeah, I don't think that'll work.  I just looked at the underlying scrollMonitor docs and it looks like that package doesn't deal with x-scrolls, so I don't think this would be a simple PR either.
