### ISSUE TITLE
Binding to a different container

### ISSUE THREAD

**Issue by mcpll** [BKWLD/vue-in-viewport-mixin#14]
With vuewport Mixinx is possibile to bind a different container that not is the BODY?
Becouse i have a container that scroll but is not the body of the page

**Comment by weotch** [comment]
It's not built to do that now, though the underlying library `scrollMonitor` does allow that

**Comment by Eh2406** [comment]
Hi, this would be very useful to me for a work project. If you have advice on how you would like this implemented I can make a PR.

**Comment by weotch** [comment]
Here's the instructions on how you'd do this with scrollMonitor: https://github.com/stutrek/scrollMonitor/#for-a-scroll-container.  You'd want to add that `scrollMonitor.createContainer()` step before this part: https://github.com/BKWLD/vue-in-viewport-mixin/blob/master/index.coffee#L86-L87.  I suggest adding another prop to the mixin, like `inViewportContainer` where you pass in a string selector for the container you want to use.  Then you use that selector in your `scrollMonitor.createContainer()`.

**Comment by Eh2406** [comment]
Wouldn't that lead to having one `containerMonitor` per tracked `elementWatcher`? I would think it would be more efficient for all the children that have a common parent to share a `containerMonitor`, but I don't know how this works internally.

**Comment by weotch** [comment]
Yeah, you'd probably want to pass in a global monitor if you wanted every instance of this mixin to use the same container ... like you might need to make this package export a function where you could call like:

```js
import { setContainer } from 'in-viewport-mixin`
setContainer('#main`)
```

**Comment by Eh2406** [comment]
With some experimentation sharing a `containerMonitor` doesn't seem to make a big performance difference in our app. I will try to make a PR with your suggestion sometime today.
