### ISSUE TITLE
Moving the element in the dom without scrolling does not recheck if the element is in the viewport

### ISSUE THREAD

**Issue by Dadibom** [BKWLD/vue-in-viewport-mixin#5]
Perhaps you could put inViewport.now etc. in computed rather than data, and check if the position has moved (and if so, update) before returning?

**Comment by weotch** [comment]
Could you describe more what you mean by "moving in the dom"?  Like touching CSS `top` / `left` with JS?

**Comment by Dadibom** [comment]
Sure, sorry. I am using this for an auto scroller. When the element is in view, more content will be loaded. However, when that content is added to the dom, causing the autoscroller element to be pushed outside the viewport, inViewport.now will remain true until the user scrolls.

**Comment by weotch** [comment]
What happens if you call `updateInViewport()` on the component you've mixed the package into AFTER the additional content has loaded?  Does that update the state?  If it doesn't, the next problem to solve is how to get [scrollMonitor](https://github.com/stutrek/scrollMonitor) (a package this one consumes) to update it's measurements.

Perhaps you could call (if my first suggestion doesn't work):

```js
this.scrollMonitor.recalculateLocation()
this.updateInViewport()
```

**Comment by Dadibom** [comment]
Doesn't work I'm afraid ):

**Comment by ca11ado** [comment]
The same problem.

- component loaded in viewport; inViewport.now === true
- another component loads big image and component now not in viewport;  Still inVieport.now === true

inViewport.now properly recalculted if I do some scroll

```
this.scrollMonitor.recalculateLocation()
this.updateInViewport()
```
doesn't work

**Comment by bluetomato** [comment]
I'm having the same issue. 
I've got a grid with lots of products, so i'm loading only images of products in viewport (or almost). if i change the product order via button and javascript, it appears that the products now in viewport don't know their new state. at least not until the user scrolls again. 

also i dont want to call a function for updating the inViewport everywhere i change the dom via javascript, the component should handle this by itself!

**Comment by weotch** [comment]
Yeah, ScrollMonitor doesn't have an API method to fully recaculate itself ... like I haven't had a lot of success with it's `recalculateLocation()` method.  _However_, I have done this on some projects to get it to recaculate:

```
window.dispatchEvent(new CustomEvent('resize'))
```

Essentially, I fake a resize event and this forces ScrollMonitor to reassess itself.

**Comment by weotch** [comment]
I'll soon be releasing a breaking 2.0 version of this package that uses the IntersectionObserver and will fix issues like this since it's not scroll based.  It's here right now: https://github.com/BKWLD/vue-in-viewport-mixin/tree/intersection-observer

**Comment by weotch** [comment]
This has been released now: https://github.com/BKWLD/vue-in-viewport-mixin/releases/tag/v2.0.0
