### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by seuck** [BKWLD/vue-in-viewport-mixin#51]
Hi, I updated this mixing to make it compatible with Vue 3.
Only old option syntax is supported as my goal was to enable Vue 3 based projects to quickly migrate without refactoring code that uses this mixin.
I also migrated project to latest version of Storybook.
Tests run ok and I'm already using it in my Vue 3 based work project.
I didn't updated Cypress too as default support for Coffescript have been dropped starting from version 4.x.

As my changes break compatibility with Vue 2, this can be considered version 3 of the mixin.
Could any maintainer kindly give me permission to open a branch and do a PR?

**Comment by weotch** [comment]
Oh, cool, thanks!  You should be able to submit a PR request from your fork without any permissions changes.

**Comment by seuck** [comment]
PR created: https://github.com/BKWLD/vue-in-viewport-mixin/pull/52

**Comment by weotch** [comment]
Released as 3.0.0, thank you!
