### ISSUE TITLE
npm module does not include compiled files

### ISSUE THREAD

**Issue by phellipelins** [BKWLD/vue-in-viewport-mixin#6]
I have tried use this mixin, but when I import using `require()`, I get this error:

`
Module parse failed: ./~/vue-in-viewport-mixin/index.coffee Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
`

**Comment by weotch** [comment]
What version are you using?  Since 1.0.1 the package.json points to the `index.js` file: https://github.com/BKWLD/vue-in-viewport-mixin/commit/a86533b74c6e3ae5afb5d59060056c72b1d4aa39

**Comment by weotch** [comment]
Ohh, I see, the retroactive tag we made of 0.6.0 is being taken as the most current when doing a fresh `yarn add` or `npm install` right now...

**Comment by weotch** [comment]
Ok, this should be fixed now, on the npm page it's now showing the right version for latest:

![](http://yo.bkwld.com/250s3X2W0r0w/Image%202017-04-21%20at%208.13.47%20AM.png)
