### ISSUE TITLE
In viewport element of the component

### ISSUE THREAD

**Issue by adyz** [BKWLD/vue-in-viewport-mixin#9]
Hi guys, 

Awesome project!

Newbie with Vue.js here!

I was wondering if this mixin can help me detect if one of the components child, an HTML element, is in view-port. 

I have a really tall component (a form with lots of inputs and I want to know when the user is close to an input so that I can show some helpers).

Thanks!

**Comment by weotch** [comment]
Not directly.  You would need to either make a new component for that child and have that use this mixin or you could use the directive version: https://github.com/BKWLD/vue-in-viewport-directive.

**Comment by weotch** [comment]
Relates to #7
